### PR TITLE
Improve code blocks

### LINKED ISSUE #29: Click to copy stops the user from copying only a small part of the code block
It is helpful to copy the entire code block with just a click. However, this happens even when I try to only copy a small part, for example one line of the code, which is not user friendly at all.

### PR DESCRIPTION
**Pull request by daniellimws**
### UI changes
* Add border around code block caption and fill with grey background color
* Make link icons appear when hovering over caption

Before:

image

After:

image

Currently the background uses a "theme-neutral" color (dark grey) because it is not possible to set it according to the chosen theme color at this point. This is because the sphinx_symbiflow_theme.css file that contains this change is generated here, and does not contain the color theme information contained in conf.py, which is freely modifiable by any project that uses this theme. @mithro Do you think this color is ok?

### Examples/documentation
* Add code block caption
* Add long line of code mentioned in https://github.com/SymbiFlow/sphinx_symbiflow_theme/pull/20#issuecomment-658798430

image

### Bugfix
* Fix #29 

Signed-off-by: Daniel Lim Wee Soong <weesoong.lim@gmail.com>

### CODE REVIEW

**Comment by daniellimws** [comment]
Modified this PR to add some UI changes

**Comment by mithro** [comment]
@daniellimws This all looks pretty awesome! -- Should the long line cause scrollbars on the code?

**Comment by mithro** [comment]
The screenshots are super awesome -- you can also link to the readthedocs generated from the pull request -- IE https://sphinx-materialdesign-theme--28.org.readthedocs.build/examples/sphinxmarkup/codeblock.html

<blockquote><div><strong><a href="https://sphinx-materialdesign-theme--28.org.readthedocs.build/examples/sphinxmarkup/codeblock.html">Code Blocks — SymbiFlow Theme 0.1.11 documentation</a></strong></div></blockquote>

**Comment by daniellimws** [comment]
@mithro I'm on MacOS so all scrollbars are hidden by default. Does it show on your side? Should I change anything?

> The screenshots are super awesome -- you can also link to the readthedocs generated from the pull request -- IE https://sphinx-materialdesign-theme--28.org.readthedocs.build/examples/sphinxmarkup/codeblock.html

I included the screenshot so that you didn't need to open it :P But ok I shall also link to the generated docs next time so that the changes can be easily found.


<blockquote><div><strong><a href="https://sphinx-materialdesign-theme--28.org.readthedocs.build/examples/sphinxmarkup/codeblock.html">Code Blocks — SymbiFlow Theme 0.1.11 documentation</a></strong></div></blockquote>

**Comment by mithro** [comment]
@daniellimws -- Looks like they do appear. Might want to make that long line a bit longer -- it doesn't cause scrollbars on my computer :-)

**Comment by daniellimws** [comment]
@mithro Let's see if this changes anything, if not I'll have to add some css for it to show

**Comment by mithro** [comment]
There is something weird going on with the scrollbars and the line numbers;
Screenshot from 2020-07-16 19-26-30

**Comment by mithro** [comment]
Need to rebase this now...

**Comment by daniellimws** [comment]
Added a quick fix for #29

**Comment by daniellimws** [comment]
@mithro The problem should be because the line numbers are aligned to the center vertically. I changed it to align to the top. Could you test if it looks correct now?

**Comment by mithro** [comment]
Screenshot from 2020-07-16 20-11-12
Screenshot from 2020-07-16 20-11-28

**Comment by mithro** [comment]
The click to copy kind of moves with the scrolling.

**Comment by daniellimws** [comment]
I think it should be ok now.

**Comment by mithro** [comment]
Click to copy looks good - there is still a very minor alignment issue with the numbers but that might always be there even when the scrollbar isn't.

**Pull request merged**
