### PR TITLE
Don't wrap lines for code blocks

### PR DESCRIPTION
**Pull request by daniellimws**
If `whitespace: pre-wrap` is set, lines that are too long will wrap to the next line, causing the line numbers to not align properly with the code.

Before:

image

Notice that the line numbers are not aligned correctly.

After:

image

### CODE REVIEW

**Comment by daniellimws** [comment]
@mithro ping

**Comment by mithro** [comment]
LGTM! We should add an example to the output in this repository.

**Comment by daniellimws** [comment]
@mithro What do you mean by example?

**Comment by mithro** [comment]
@daniellimws A code block which has a very long line @ https://github.com/SymbiFlow/sphinx_symbiflow_theme/blob/master/example/examples/sphinxmarkup/codeblock.rst

<blockquote><div> GitHub</div><div><strong><a href="https://github.com/SymbiFlow/sphinx_symbiflow_theme">SymbiFlow/sphinx_symbiflow_theme</a></strong></div><div>Material Design Html Theme for Sphinx. Contribute to SymbiFlow/sphinx_symbiflow_theme development by creating an account on GitHub.</div></blockquote>

**Comment by daniellimws** [comment]
Ah ok

**Pull request merged**
